### ISSUE TITLE
Error while installing 1.0.3

### ISSUE THREAD

**Issue by rfesty** [Swrve/swrve-sdk-integrations#11]
Running:
cordova plugin add plugins/SwrvePlugin

Getting:
Error: Uh oh!
"*****/plugins/com.swrve.SwrvePlugin/platforms/ios/SwrveSDK/SwrveSDKCommon/Common/Permissions/ISHPermissionRequest+All.m" not found!

Thanks

**Comment by Sergio-Mira** [comment]
Hi @rfesty the iOS SDK module is now a git submodule in the repository. I've checked that the code is not pulled in the zip that Github offers, you can:
1. Checkout the git repo and run
`git submodule update --init --recursive`
2. Download the release-4_6-2 from swrve-ios-sdk https://github.com/Swrve/swrve-ios-sdk/archive/release-4_6_2.zip and put it in the /plugins/com.swrve.SwrvePlugin/platforms/ios/SwrveSDK/ folder

I'll update the readme and create a release zip that has that source in it, for this and upcoming releases and mention it in the integration docs.

Let me know how it goes!

**Comment by Sergio-Mira** [comment]
https://github.com/Swrve/swrve-sdk-integrations/releases/download/phonegap-1.0.3/phonegap-wrapper-1.0.3.zip
